spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/riskhunter?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: NJUSE2023
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

model:
  # 由于资金问题，RiskHunter的Token额度有限，我们建议您使用自己的app-id和api-key
  api-key: sk-b8a9162d68384b82aefde24d2218966f
  # 普通对话服务配置
  deepseek:
    base-url:  https://dashscope.aliyuncs.com/compatible-mode/v1
  # RAG服务配置
  dashscope:
    base-url: https://dashscope.aliyuncs.com
    app-id: fe21741cec104e6a83226e989de14eb6
    rag-pipeline-id: wwzvnuysgw